spring.application.name=libreria
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/db_library
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Esto ayuda a Spring a crear las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
#Seguridad
spring.security.user.name=user
spring.secutity.user.password=pass
#Crear automaticamente la tabla usuarios en MySQL
spring.jpa.generate-ddl=true